### ISSUE TITLE
简历请求

### ISSUE THREAD

**Issue by linonetwo** [dkqkxx/dkqkxx.github.io#1]
您好，在 v2ex 看到您回的帖子，不过主页上没看到邮箱。有兴趣的话可以给我发个邮件带上简历，谢谢。

**Comment by dkqkxx** [comment]
邮箱  ***@***.***
简历如附件，24届硕士在读，自然语言处理方向，即将毕业
也可以接受后端方向相关工作

lin onetwo ***@***.***> 于2023年10月22日周日 21:25写道：

**Comment by linonetwo** [comment]
发到 [linonetwo012@gmail.com](mailto:linonetwo012@gmail.com) 吧，回复这个 issue 看起来并不能带上附件！
